language: java

dist: trusty

jdk:
  - oraclejdk8

# Init xvfb for headless GUI testing on trusty
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

install:
  - cp .travis.settings.xml ${HOME}/.m2/settings.xml
